[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.12.0", features = ["full"]}
mini-redis = "0.4.1"
bytes = "1.1.0"
